name: Build and deploy

on:
  push:
    branches:
      - main
    paths:
      - 'prueba-tres/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build
        run: |
          cd prueba-tres
          docker build -t nginx .

      - name: Deploy
        run: |
          docker push nginx
