name: Build and deploy

on:
  push:
    branches:
      - main
    paths:
      - 'prueba-tres/**'
      - '.github/workflows/main.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get install -y build-essential
          echo "Installed build-essential"

      - name: Build & Deploy
        run: |
          docker-compose up -d --build
          echo "Build & Deploy done."
        working-directory: ./prueba-tres