name: Build and deploy

on:
  push:
    branches:
      - main
    paths:
      - 'prueba-tres/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          ls -la
          sudo apt-get install -y build-essential

      - name: Build
        run: |
          docker build -t nginx .
        working-directory: prueba-tres

      - name: Deploy
        run: |
          docker push nginx